
server:
  port: 443
  address: 0.0.0.0
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: gkachfha
    key-store-type: PKCS12
spring:
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
  config:
    import: "classpath:application-db.yml"

